# Bitcoin daemons

# Test
TESTNET_USERNAME = 'bitcoinrpc'
TESTNET_PASSWORD = 'REDACTED'
TESTNET_HOST = 'ec2-52-29-69-203.eu-central-1.compute.amazonaws.com'
TESTNET_PORT = '18331'

# Regtest
REGTEST_USERNAME = 'bitcoinrpc'
REGTEST_PASSWORD = 'REDACTED'
REGTEST_HOST = 'ec2-52-29-16-192.eu-central-1.compute.amazonaws.com'
REGTEST_PORT = '18331'

# Staging - Lets use the linode node for now
#STAGING_USERNAME = 'bitcoinrpc'
#STAGING_PASSWORD = 'REDACTED'
#STAGING_HOST = '212.111.43.207'
#STAGING_PORT = '8332'

STAGING_USERNAME = "bitcoinrpc"
STAGING_PASSWORD = "REDACTED"
STAGING_HOST = "ec2-52-28-63-126.eu-central-1.compute.amazonaws.com"
STAGING_PORT = "8331"

# Main
MAINNET_USERNAME = 'bitcoinrpc'
MAINNET_PASSWORD = 'REDACTED'
MAINNET_HOST = 'ec2-52-29-0-37.eu-central-1.compute.amazonaws.com'
MAINNET_PORT = '8331'

# Bitcoin wallets

# Test
TESTNET_REFILL_ADDRESS = 'mhyCaF2HFk7CVwKmyQ8TahgVdjnHSr1pTv'
TESTNET_REFILL_PASSWORD = 'REDACTED'
TESTNET_FEDERATION_ADDRESS = 'mqXz83H4LCxjf2ie8hYNsTRByvtfV43Pa7'
TESTNET_FEDERATION_PASSWORD = 'REDACTED'

# Regtest
REGTEST_REFILL_ADDRESS = 'mkvZ4qs7f83WQ2RT5up6Tv7SMwrFgFon7k'
REGTEST_REFILL_PASSWORD = 'REDACTED'
REGTEST_FEDERATION_ADDRESS = 'mh8jtRZ2RYPeH9DzLobmbGByKjY7nssC5R'
REGTEST_FEDERATION_PASSWORD = 'REDACTED'

# Staging
STAGING_REFILL_ADDRESS = '12udvE3zmbQLhtSGZUqqAvGWSKDUCpbgoq'
STAGING_REFILL_PASSWORD = 'REDACTED'
STAGING_FEDERATION_ADDRESS = '12udvE3zmbQLhtSGZUqqAvGWSKDUCpbgoq'
STAGING_FEDERATION_PASSWORD = 'REDACTED'

# Mainnet
MAINNET_REFILL_ADDRESS = '12udvE3zmbQLhtSGZUqqAvGWSKDUCpbgoq'
MAINNET_REFILL_PASSWORD = 'REDACTED'
# MAINNET_REFILL_ADDRESS = '1JttRRdtAi6cDNM23Uq4BEU61R8kJeANJs'
# MAINNET_REFILL_PASSWORD = 'REDACTED'
MAINNET_FEDERATION_ADDRESS = 'REDACTED'
MAINNET_FEDERATION_PASSWORD = 'REDACTED'
